### ISSUE TITLE
CV Upload Error

### ISSUE THREAD

**Issue by vihanga-liyanage** [UCSC-LK/CV-APP-2017#13]
Upload CV -> delete file from back end -> Try to upload again
This could happen due to some reasons. And this error could occur from many other paths. This is just an example. Log is as follows.
```
Uploading file...
Uploading file complete.
Deleting old file Vihanga-Liyanage.pdf
/home/vihanga/Projects/CV-APP-2017/server/app/controller/cv-controller.js:21
                if (err) return next(err);
                                ^

ReferenceError: next is not defined
    at /home/vihanga/Projects/CV-APP-2017/server/app/controller/cv-controller.js:21:33
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by chamathsilva** [comment]
2e14222d423b26bf2ec3f957cba9cf4cb2f45f64
